# Generated by Django 3.1.2 on 2020-10-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Aptitude', 'Aptitude'), ('Programming', 'Programming')], default='None', max_length=30),
        ),
    ]
