# Generated by Django 3.1.4 on 2021-01-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.college'),
        ),
    ]
